### ISSUE TITLE
Implemented: https://esphome.io/components/sensor/xiaomi_ble.html#mjyd02yl-a

### ISSUE THREAD

**Issue by johnjoemorgan** [esphome/bluetooth-proxies#25]
Implemented: https://esphome.io/components/sensor/xiaomi_ble.html#mjyd02yl-a

_Originally posted by @nagyrobi in https://github.com/esphome/feature-requests/issues/732#issuecomment-1175029654_

Just set up my Atom Mini in:

 Home Assistant 2022.9.7 Supervisor 2022.09.1 Operating System 9.0 Frontend 20220907.2 - latest 

I have the Mini set up as follows but I'm getting no status or updates from the mjyd02yl-a

```
substitutions:
  name: atom-mini
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/m5stack-atom-lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

logger:
  level: VERBOSE
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

sensor:

binary_sensor:
  - platform: xiaomi_mjyd02yla
    name: "Night Light"
    mac_address: "XX:4D:3E:CA:XX:XX"
    bindkey: "XXXXe6c1d891bd1b7097bac3801c68f"
    idle_time:
      name: "MJYD02YL-A Idle Time"
    light:
      name: "MJYD02YL-A Light Status"
    battery_level:
      name: "MJYD02YL-A Battery Level"
    illuminance:
      name: "MJYD02YL-A Illuminance"      
```
