### ISSUE TITLE
[active] is an invalid option for [bluetooth_proxy]. Please check the indentation.

### ISSUE THREAD

**Issue by ziolelle** [esphome/bluetooth-proxies#33]
Using ESPHOME 2022.9.7

MY Config:
```
substitutions:
  name: esp32-bluetooth-proxy-xxxxxxxxxx
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: "xxxxxxxxxxxxxxxxxxx"
  password: "xxxxxxxxxxxxxxxxxxxxxx"
  fast_connect: on

# Enable logging
logger:
  level: DEBUG

switch:
  - platform: restart
    name: "${name} Restart"

sensor:
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
```

trying to validate the config in HomeAssistant AddOn or also using command line esphome, the config gives:

<img width="738" alt="Screenshot 2022-10-05 at 08 31 20" src="https://user-images.githubusercontent.com/24245403/193995691-c2b6a4f1-7119-4ae1-bfc8-072bace4ed72.png">
