### ISSUE TITLE
olimex-bluetooth-proxy connection issues

### ISSUE THREAD

**Issue by marc-gist** [esphome/bluetooth-proxies#43]
I get CONSTANT disconnect, connect on the proxy.  Network is fine, and happens to various HA instances I have tested it on.

![image](https://user-images.githubusercontent.com/4084427/194879772-e15faa11-ab3c-4a42-9b45-f94022819f4f.png)

Nothing in the logs except:
```
WARNING GPIO12 is a Strapping PIN and should be avoided.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
```

Logs also contantly disconnect and reconnect.
```
INFO 10.20.1.31: Error while reading incoming messages: Error while reading data: [Errno 104] Connection reset by peer
INFO 10.20.1.31: Ping Failed: Error while reading data: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for 10.20.1.31
```

Both static and dynamic ips tend to do this :(

**Comment by nagyrobi** [comment]
Try with `active: false` for both `esp32_ble_tracker scan_parameters` and `bluetooth_proxy`.

**Comment by marc-gist** [comment]
> Try with `active: false` for both `esp32_ble_tracker scan_parameters` and `bluetooth_proxy`.

Doesn't the defeat the purpose of this device? That's all it supposed to do is scan and be a proxy.
What's the point in this test?

Thanks

**Comment by tomi19921702** [comment]
Got the same problem tried 3 different boards, changed yaml template with a few different settings Removed Esp board from the Device list.

**Comment by marc-gist** [comment]
> Got the same problem tried 3 different boards, changed yaml template with a few different settings Removed Esp board from the Device list.

So you fixed it or gave up? 🙂

**Comment by nagyrobi** [comment]
@marc-gist it depends on your use case. If you're just gathering sensor data passively you don't need active mode at all.
What device are you using it with?

**Comment by nagyrobi** [comment]
```
Please add the following sensors to your config and re-flash the board:
sensor:
- platform: template
  name: "Free Heap Memory"
  lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
  icon: "mdi:memory"
  entity_category: diagnostic
  state_class: measurement
  unit_of_measurement: "b"
  update_interval: 60s
- platform: uptime
  name: "Uptime"
```
And see if memory consumption stays constant or not, also check uptimes, does it reboot itself often?
