### ISSUE TITLE
Trying to add DHT sensor to same ESP32 running a bluetooth proxy

### ISSUE THREAD

**Issue by tejasitraj** [esphome/bluetooth-proxies#84]
Hi, I have successfully installed a bluetooth proxy on a generic ESP32. I have adopted it in ESPHome, set a static IP and encryption key, and added it to Home Assistant. Also tested it with my Oral B toothbrush and all works fine! So far so good. 
I am now trying to add a DHT22 sensor to the same ESP32, using the following yaml code in esphome:

```
sensor:
  - platform: dht
    pin: $dht_pin
    temperature:
      name: "Storage Room Temperature"
      id: inside_temperature
      filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
    humidity:
      name: "Storage Room Humidity"
      filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
    model: DHT22
    update_interval: 30s

```
[logs_esp32-bluetooth-proxy-8da23c_run.txt](https://github.com/esphome/bluetooth-proxies/files/11585574/logs_esp32-bluetooth-proxy-8da23c_run.txt)

But get the attached error during compilation in ESPHome. Is it possible to add a sensor to the same ESP32 or not?
Thank you!
